In [14]:
import pandas as pd


df = pd.read_csv("posts.tsv", sep="\t")
user_df = pd.DataFrame(columns=["Name", "Job Title", "Email", "Department", "Profile Picture", "Bio", "Research Interests", "Website"])
user_df["Name"] = df["User"].unique()
user_df["Job Title"] = "Test"
user_df["Email"] = "test@broadinstitute.org"
user_df["Department"] = "Department of Test"
user_df["Profile Picture"] = "None"
user_df.to_csv("users.tsv", sep="\t", index=False)
user_df

,Name,Job Title,Email,Department,Profile Picture,Bio,Research Interests,Website
0,User1,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
1,Kenneth P Olive,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
2,Daniel Herranz,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
3,Francisco Garcia-Garcia,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
4,Makenzy L Mull,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
131,Simon Kozlov,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
132,Matthew McPartlon,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
133,Joshua Meier,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
134,"Owen Queen, Yepeng Huang, Marinka Zitnik",Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN
135,Marinka Zitnik,Test,test@broadinstitute.org,Department of Test,None,NaN,NaN,NaN